#############################################################################
# Makefile for building: mUnit
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  mUnit.pro
# Template: app
# Command: c:\qt\5.14.2\bin\qmake.exe -o Makefile mUnit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = c:\qt\5.14.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = c:\qt\5.14.2\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = c:\qt\5.14.2\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = mUnit.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: mUnit.pro C:\qt\5.14.2\mkspecs\win32-msvc\qmake.conf C:\qt\5.14.2\mkspecs\features\spec_pre.prf \
		C:\qt\5.14.2\mkspecs\common\angle.conf \
		C:\qt\5.14.2\mkspecs\common\windows-desktop.conf \
		C:\qt\5.14.2\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\qt\5.14.2\mkspecs\common\windows-vulkan.conf \
		C:\qt\5.14.2\mkspecs\common\msvc-desktop.conf \
		C:\qt\5.14.2\mkspecs\qconfig.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3danimation.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dcore.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dextras.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dinput.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquick.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3drender.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axbase.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axserver.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_bodymovin_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_charts.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_charts_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_concurrent.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_core.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_core_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_dbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_gamepad.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_gui.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_gui_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_help.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_help_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_location.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_location_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_multimedia.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_network.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_network_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_networkauth.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_nfc.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_opengl.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_positioning.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_printsupport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_purchasing.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qml.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qml_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmltest.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3d.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3d_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3drender.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3drender_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dutils.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quick_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_repparser.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_script.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_script_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_scripttools.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_scxml.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_sensors.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_serialbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_serialport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_sql.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_sql_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_svg.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_svg_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_testlib.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_uitools.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_webchannel.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_websockets.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_webview.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_webview_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_widgets.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_winextras.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_xml.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_xml_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_assimp.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_assimpsceneimport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_defaultgeometryloader.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_dsengine.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfgeometryloader.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfsceneexport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfsceneimport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qdirect2d.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qgif.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qicns.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qico.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qjpeg.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qminimal.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_debugger.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_local.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_messages.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_native.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_nativedebugger.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_preview.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_profiler.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_server.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qoffscreen.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsgd3d12backend.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlite.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlmysql.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlodbc.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsvg.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsvgicon.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtaudio_wasapi.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtexttospeech_sapi.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtga.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_esri.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_itemsoverlay.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtiff.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtpassthrucanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtpeakcanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_winrt.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsysteccanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qttinycanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvectorcanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualcanbus.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_hangul.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_openwnn.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_pinyin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_tcime.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_thai.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwbmp.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwebgl.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwebp.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwindows.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwindowsvistastyle.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_qxdgdesktopportal.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_scene2d.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_uip.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_wmfengine.pri \
		C:\qt\5.14.2\mkspecs\modules\qt_plugin_xinputgamepad.pri \
		C:\qt\5.14.2\mkspecs\features\qt_functions.prf \
		C:\qt\5.14.2\mkspecs\features\qt_config.prf \
		C:\qt\5.14.2\mkspecs\win32-msvc\qmake.conf \
		C:\qt\5.14.2\mkspecs\features\spec_post.prf \
		C:\qt\5.14.2\mkspecs\features\exclusive_builds.prf \
		C:\qt\5.14.2\mkspecs\common\msvc-version.conf \
		C:\qt\5.14.2\mkspecs\features\toolchain.prf \
		C:\qt\5.14.2\mkspecs\features\default_pre.prf \
		C:\qt\5.14.2\mkspecs\features\win32\default_pre.prf \
		C:\qt\5.14.2\mkspecs\features\resolve_config.prf \
		C:\qt\5.14.2\mkspecs\features\exclusive_builds_post.prf \
		C:\qt\5.14.2\mkspecs\features\default_post.prf \
		C:\qt\5.14.2\mkspecs\features\precompile_header.prf \
		C:\qt\5.14.2\mkspecs\features\warn_on.prf \
		C:\qt\5.14.2\mkspecs\features\qt.prf \
		C:\qt\5.14.2\mkspecs\features\resources_functions.prf \
		C:\qt\5.14.2\mkspecs\features\resources.prf \
		C:\qt\5.14.2\mkspecs\features\moc.prf \
		C:\qt\5.14.2\mkspecs\features\win32\opengl.prf \
		C:\qt\5.14.2\mkspecs\features\uic.prf \
		C:\qt\5.14.2\mkspecs\features\qmake_use.prf \
		C:\qt\5.14.2\mkspecs\features\file_copies.prf \
		C:\qt\5.14.2\mkspecs\features\win32\windows.prf \
		C:\qt\5.14.2\mkspecs\features\testcase_targets.prf \
		C:\qt\5.14.2\mkspecs\features\exceptions.prf \
		C:\qt\5.14.2\mkspecs\features\yacc.prf \
		C:\qt\5.14.2\mkspecs\features\lex.prf \
		mUnit.pro \
		C:\qt\5.14.2\plugins\styles\qwindowsvistastyle.prl \
		C:\qt\5.14.2\plugins\platforms\qwindows.prl \
		C:\qt\5.14.2\plugins\imageformats\qgif.prl \
		C:\qt\5.14.2\plugins\imageformats\qicns.prl \
		C:\qt\5.14.2\plugins\imageformats\qico.prl \
		C:\qt\5.14.2\plugins\imageformats\qjpeg.prl \
		C:\qt\5.14.2\plugins\imageformats\qtga.prl \
		C:\qt\5.14.2\plugins\imageformats\qtiff.prl \
		C:\qt\5.14.2\plugins\imageformats\qwbmp.prl \
		C:\qt\5.14.2\plugins\imageformats\qwebp.prl \
		C:\qt\5.14.2\lib\Qt5Widgets.prl \
		C:\qt\5.14.2\lib\Qt5Gui.prl \
		C:\qt\5.14.2\lib\Qt5Core.prl \
		C:\qt\5.14.2\lib\qtmain.prl \
		.qmake.stash \
		C:\qt\5.14.2\mkspecs\features\build_pass.prf \
		C:\qt\5.14.2\plugins\styles\qwindowsvistastyled.prl \
		C:\qt\5.14.2\plugins\platforms\qwindowsd.prl \
		C:\qt\5.14.2\plugins\imageformats\qgifd.prl \
		C:\qt\5.14.2\plugins\imageformats\qicnsd.prl \
		C:\qt\5.14.2\plugins\imageformats\qicod.prl \
		C:\qt\5.14.2\plugins\imageformats\qjpegd.prl \
		C:\qt\5.14.2\plugins\imageformats\qtgad.prl \
		C:\qt\5.14.2\plugins\imageformats\qtiffd.prl \
		C:\qt\5.14.2\plugins\imageformats\qwbmpd.prl \
		C:\qt\5.14.2\plugins\imageformats\qwebpd.prl \
		C:\qt\5.14.2\lib\Qt5Widgetsd.prl \
		C:\qt\5.14.2\lib\Qt5Guid.prl \
		C:\qt\5.14.2\lib\Qt5Cored.prl \
		C:\qt\5.14.2\lib\qtmaind.prl
	$(QMAKE) -o Makefile mUnit.pro
C:\qt\5.14.2\mkspecs\features\spec_pre.prf:
C:\qt\5.14.2\mkspecs\common\angle.conf:
C:\qt\5.14.2\mkspecs\common\windows-desktop.conf:
C:\qt\5.14.2\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\qt\5.14.2\mkspecs\common\windows-vulkan.conf:
C:\qt\5.14.2\mkspecs\common\msvc-desktop.conf:
C:\qt\5.14.2\mkspecs\qconfig.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3danimation.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dcore.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dextras.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dinput.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dlogic.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquick.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3drender.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_3drender_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axbase.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axbase_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axcontainer.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axserver.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_axserver_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_bluetooth.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_bodymovin_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_charts.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_charts_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_concurrent.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_core.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_core_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_datavisualization.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_dbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_dbus_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_gamepad.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_gui.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_gui_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_help.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_help_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_location.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_location_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_multimedia.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_network.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_network_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_networkauth.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_nfc.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_nfc_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_opengl.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_opengl_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_openglextensions.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_positioning.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_positioning_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_positioningquick.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_printsupport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_purchasing.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qml.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qml_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmltest.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlworkerscript.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3d.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3d_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dassetimport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3drender.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3drender_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3druntimerender.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dutils.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick3dutils_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quick_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_repparser.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_repparser_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_script.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_script_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_scripttools.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_scxml.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_scxml_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_sensors.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_sensors_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_serialbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_serialport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_serialport_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_sql.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_sql_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_svg.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_svg_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_testlib.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_testlib_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_texttospeech.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_uiplugin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_uitools.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_uitools_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_virtualkeyboard.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_webchannel.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_websockets.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_websockets_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_webview.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_webview_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_widgets.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_widgets_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_winextras.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_winextras_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_xml.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_xml_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_lib_zlib_private.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_assimp.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_assimpsceneimport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_defaultgeometryloader.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_dsengine.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfgeometryloader.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfsceneexport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_gltfsceneimport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qdirect2d.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qgenericbearer.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qgif.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qicns.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qico.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qjpeg.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qminimal.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_debugger.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_local.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_messages.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_native.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_nativedebugger.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_preview.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_profiler.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_server.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qoffscreen.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsgd3d12backend.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlite.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlmysql.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsqlodbc.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsvg.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qsvgicon.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtaudio_wasapi.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtexttospeech_sapi.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtga.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_esri.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_itemsoverlay.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtiff.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtpassthrucanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtpeakcanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtposition_winrt.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtsysteccanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qttinycanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvectorcanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualcanbus.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_hangul.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_openwnn.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_pinyin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_tcime.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboard_thai.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwbmp.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwebgl.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwebp.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwindows.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qwindowsvistastyle.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_qxdgdesktopportal.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_scene2d.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_uip.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_wmfengine.pri:
C:\qt\5.14.2\mkspecs\modules\qt_plugin_xinputgamepad.pri:
C:\qt\5.14.2\mkspecs\features\qt_functions.prf:
C:\qt\5.14.2\mkspecs\features\qt_config.prf:
C:\qt\5.14.2\mkspecs\win32-msvc\qmake.conf:
C:\qt\5.14.2\mkspecs\features\spec_post.prf:
C:\qt\5.14.2\mkspecs\features\exclusive_builds.prf:
C:\qt\5.14.2\mkspecs\common\msvc-version.conf:
C:\qt\5.14.2\mkspecs\features\toolchain.prf:
C:\qt\5.14.2\mkspecs\features\default_pre.prf:
C:\qt\5.14.2\mkspecs\features\win32\default_pre.prf:
C:\qt\5.14.2\mkspecs\features\resolve_config.prf:
C:\qt\5.14.2\mkspecs\features\exclusive_builds_post.prf:
C:\qt\5.14.2\mkspecs\features\default_post.prf:
C:\qt\5.14.2\mkspecs\features\precompile_header.prf:
C:\qt\5.14.2\mkspecs\features\warn_on.prf:
C:\qt\5.14.2\mkspecs\features\qt.prf:
C:\qt\5.14.2\mkspecs\features\resources_functions.prf:
C:\qt\5.14.2\mkspecs\features\resources.prf:
C:\qt\5.14.2\mkspecs\features\moc.prf:
C:\qt\5.14.2\mkspecs\features\win32\opengl.prf:
C:\qt\5.14.2\mkspecs\features\uic.prf:
C:\qt\5.14.2\mkspecs\features\qmake_use.prf:
C:\qt\5.14.2\mkspecs\features\file_copies.prf:
C:\qt\5.14.2\mkspecs\features\win32\windows.prf:
C:\qt\5.14.2\mkspecs\features\testcase_targets.prf:
C:\qt\5.14.2\mkspecs\features\exceptions.prf:
C:\qt\5.14.2\mkspecs\features\yacc.prf:
C:\qt\5.14.2\mkspecs\features\lex.prf:
mUnit.pro:
C:\qt\5.14.2\plugins\styles\qwindowsvistastyle.prl:
C:\qt\5.14.2\plugins\platforms\qwindows.prl:
C:\qt\5.14.2\plugins\imageformats\qgif.prl:
C:\qt\5.14.2\plugins\imageformats\qicns.prl:
C:\qt\5.14.2\plugins\imageformats\qico.prl:
C:\qt\5.14.2\plugins\imageformats\qjpeg.prl:
C:\qt\5.14.2\plugins\imageformats\qtga.prl:
C:\qt\5.14.2\plugins\imageformats\qtiff.prl:
C:\qt\5.14.2\plugins\imageformats\qwbmp.prl:
C:\qt\5.14.2\plugins\imageformats\qwebp.prl:
C:\qt\5.14.2\lib\Qt5Widgets.prl:
C:\qt\5.14.2\lib\Qt5Gui.prl:
C:\qt\5.14.2\lib\Qt5Core.prl:
C:\qt\5.14.2\lib\qtmain.prl:
.qmake.stash:
C:\qt\5.14.2\mkspecs\features\build_pass.prf:
C:\qt\5.14.2\plugins\styles\qwindowsvistastyled.prl:
C:\qt\5.14.2\plugins\platforms\qwindowsd.prl:
C:\qt\5.14.2\plugins\imageformats\qgifd.prl:
C:\qt\5.14.2\plugins\imageformats\qicnsd.prl:
C:\qt\5.14.2\plugins\imageformats\qicod.prl:
C:\qt\5.14.2\plugins\imageformats\qjpegd.prl:
C:\qt\5.14.2\plugins\imageformats\qtgad.prl:
C:\qt\5.14.2\plugins\imageformats\qtiffd.prl:
C:\qt\5.14.2\plugins\imageformats\qwbmpd.prl:
C:\qt\5.14.2\plugins\imageformats\qwebpd.prl:
C:\qt\5.14.2\lib\Qt5Widgetsd.prl:
C:\qt\5.14.2\lib\Qt5Guid.prl:
C:\qt\5.14.2\lib\Qt5Cored.prl:
C:\qt\5.14.2\lib\qtmaind.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mUnit.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) mUnit.vc.pdb
	-$(DEL_FILE) mUnit.ilk
	-$(DEL_FILE) mUnit.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\mUnit\munit_plugin_import.cpp .qmake.stash mUnit.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
